### ISSUE TITLE
MapDBHelper.getZoneAssocFromExtPoi throw  unable to open database file

### ISSUE THREAD

**Issue by theGlenn** [Insiteo/Android#3]
Hi !

Calling the `MapDBHelper.getZoneAssocFromExtPoi()` function throw the following sqlite error

```
android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file
            at android.database.sqlite.SQLiteDatabase.dbopen(Native Method)
            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1125)
            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1076)
            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1052)
            at com.insiteo.lbs.common.database.a.open(SourceFile:88)
            at com.insiteo.lbs.common.init.InitProvider.registerDBHelper(SourceFile:474)
            at com.insiteo.lbs.map.database.MapDBHelper.getInstance(SourceFile:41)
            at com.insiteo.lbs.map.database.MapDBHelper.a(SourceFile:283)
            at com.insiteo.lbs.map.database.MapDBHelper.getZoneAssocFromExtPoi(SourceFile:277)
            at com.myqaa.beacon.insiteo.InsiteoFragment.onCreate(InsiteoFragment.java:127)
            at android.support.v4.app.Fragment.performCreate(Fragment.java:1763)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:913)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:454)
            at android.os.Handler.handleCallback(Handler.java:605)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4517)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
            at dalvik.system.NativeStart.main(Native Method)
```

I checked and I got the right permissions : 
 `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`

Thanks in advance !

**Comment by mathieu-morel** [comment]
Hi,

Did you cheked if you have the same issue in the <code>SampleApp</code> when trying to locate an external POI ?

**Comment by theGlenn** [comment]
Ok I think I was calling the function too early in the loading process it's fixed :)
Maybe throwing an error about data not being fully loaded could be a better indication. :+1:
