### ISSUE TITLE
TOP-LEVEL EXCEPTION: com.android.dex.DexException: Multiple dex files define

### ISSUE THREAD

**Issue by theGlenn** [Insiteo/Android#8]
Hi,

I'm trying to integrate Insiteo into an updated version of our project and I get the `DexException`.

```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/protobuf/AbstractMessage$1;
    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
    at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
    at com.android.dx.command.dexer.Main.run(Main.java:246)
    at com.android.dx.command.dexer.Main.main(Main.java:215)
    at com.android.dx.command.Main.main(Main.java:106)
```

I had no problem with the previous one because I had a few number of dependencies and only `com.google.android.gms:play-service` was conflicting.

```
    compile 'com.android.support:support-v4:21.0.3'
    compile 'com.mcxiaoke.volley:library-aar:1.0.0'


    compile('com.google.android.gms:play-services:6.5.87') {
        exclude group: 'com.google.android', module: 'support-v4'
    }

    compile project(':lbsLib-3.3.0_RC1_vc3')
```

Now I have a lot of gradle dependencies. I tried to exclude all support-v4 import but still doesn't work. And excluding others library imports is NOT a good solution at all... Your library should NOT impact others libraries/dependencies lifecycle.

```
    compile("com.android.support:appcompat-v7:22.2.0"){
        exclude group: 'com.google.android', module: 'support-v4'
    }
    compile("com.android.support:support-annotations:22.2.0"){
        exclude group: 'com.google.android', module: 'support-v4'
    }
    compile ('com.android.support:cardview-v7:22.2.0'){
        exclude group: 'com.google.android', module: 'support-v4'
    }
    compile("com.android.support:recyclerview-v7:22.2.0"){
        exclude group: 'com.google.android', module: 'support-v4'
    }
    compile ("com.android.support:design:22.2.0"){
        exclude group: 'com.google.android', module: 'support-v4'
    }
    compile('com.google.android.gms:play-services:6.5.87') {
        exclude group: 'com.google.android', module: 'support-v4'
    }

    compile('com.jakewharton:butterknife:7.0.1'){
        exclude group: 'com.google.android', module: 'support-v4'
    }
    compile('com.github.bumptech.glide:glide:3.6.0'){
        exclude group: 'com.google.android', module: 'support-v4'
    }
    compile('jp.co.cyberagent.android.gpuimage:gpuimage-library:1.2.3'){
        exclude group: 'com.google.android', module: 'support-v4'
    }

    compile('com.squareup.retrofit:retrofit:1.9.0'){
        exclude group: 'com.google.android', module: 'support-v4'
    }
    compile('com.squareup.okhttp:okhttp:2.2.0'){
        exclude group: 'com.google.android', module: 'support-v4'
    }
    compile('com.mcxiaoke.volley:library-aar:1.0.0'){
        exclude group: 'com.google.android', module: 'support-v4'
    }

    compile('com.afollestad:material-dialogs:0.7.6.0'){
        exclude group: 'com.google.android', module: 'support-v4'
    }
    compile('it.neokree:MaterialTabs:0.11'){
        exclude group: 'com.google.android', module: 'support-v4'
    }

    compile('com.sothree.slidinguppanel:library:3.0.0'){
        exclude group: 'com.google.android', module: 'support-v4'
    }

    compile project(':lbsLib-3.3.0')
```

**Comment by Insiteo** [comment]
Hi,

I have added some of your dependencies to the SampleApp application but I was not able to reproduce the `DexException` you have mentioned. Here is my `build.gradle` dependencies section:

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile project(':lbsLib-3.3.0_vc2')
    compile('de.keyboardsurfer.android.widget:crouton:1.8.5@aar')

    compile("com.android.support:appcompat-v7:22.2.0")
    compile ('com.android.support:cardview-v7:22.2.0')
    compile("com.android.support:recyclerview-v7:22.2.0")
    compile ("com.android.support:design:22.2.0")
    compile('com.google.android.gms:play-services:6.5.87')

    compile('com.squareup.retrofit:retrofit:1.9.0')
    compile('com.squareup.okhttp:okhttp:2.2.0')
    compile 'com.mcxiaoke.volley:library:1.0.18'
    compile('com.afollestad:material-dialogs:0.7.6.0')
    compile('it.neokree:MaterialTabs:0.11')
    compile('com.sothree.slidinguppanel:library:3.0.0')
}
```

I have replaced the `volley.aar` library link with a remote dependency and removed all the `exclude group: 'com.google.android', module: 'support-v4'` as it is not this library that should be causing the issues. Do you know what is the library causing the conflict or can you reproduce it on the SampleApp ?

**Comment by theGlenn** [comment]
I switched to the last release of the SDL which seems to have the dex merger issues solved.
Thanks for your answer
